"""Promote an optimizer winner into a benchmark profile.

The optimizer (registry sweep or guided search) finds the best launch
shape; the capacity benchmark runs off a hardware profile YAML. This
module closes the loop: build a ``config/profiles/optimized-*.yaml``
from a winner so "benchmark with these settings" is one click instead
of a hand-transcription (which is where numbers get mistyped).

Both promoters funnel through the same arg parser: flags the profile
schema models directly (TP, gpu-memory-utilization, max-model-len,
quantization) become profile fields; everything else rides in
``vllm_extra_flags`` verbatim, so nothing the optimizer measured gets
silently dropped.

Honesty note: the benchmark's vllm_cuda engine drives ONE server. A
winner with dp>1 (multiple replicas) is promoted pinned to replica 0's
devices, with the dp shape recorded as a warning in the YAML header —
whole-box multi-replica benchmarking is a separate engine feature.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import yaml

PROFILES_DIR = Path("config/profiles")
DEFAULT_GPU_IMAGE = "vllm/vllm-openai:latest"

# Flags lifted out of an arg list into first-class profile fields.
_FIELD_FLAGS = {
    "--tensor-parallel-size": ("tensor_parallel_size", int),
    "--gpu-memory-utilization": ("gpu_memory_utilization", float),
    "--max-model-len": ("max_model_len", int),
    "--quantization": ("quantization_kind", str),
}


class PromoteError(ValueError):
    """No promotable winner, or a shape the profile schema can't hold."""


def parse_engine_args(args: list[str]) -> tuple[dict, list[str]]:
    """Split a vLLM arg list into (profile fields, leftover flags)."""
    fields: dict[str, Any] = {}
    leftover: list[str] = []
    i = 0
    while i < len(args):
        a = str(args[i])
        if a in _FIELD_FLAGS and i + 1 < len(args):
            name, cast = _FIELD_FLAGS[a]
            try:
                fields[name] = cast(args[i + 1])
            except ValueError:
                leftover += [a, str(args[i + 1])]
            i += 2
        else:
            leftover.append(a)
            i += 1
    return fields, leftover


def _parse_gpus(gpus: Optional[str]) -> Optional[list[int]]:
    """'device=0,1' -> [0, 1]; 'all'/None -> None (no pin)."""
    if not gpus or gpus == "all":
        return None
    return [int(x) for x in gpus.removeprefix("device=").split(",") if x != ""]


def _slug(text: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "-" for c in text).strip("-").lower()


def _write_profile(
    *,
    name_hint: str,
    model_id: str,
    engine_fields: dict,
    extra_flags: list[str],
    gpu_device_ids: Optional[list[int]],
    provenance: list[str],
    warnings: list[str],
    out_dir: Path,
    # dp>1 winners: one GPU-id list per replica → the multi-replica
    # engine benchmarks the WHOLE BOX instead of one pinned replica.
    replica_devices: Optional[list[list[int]]] = None,
) -> tuple[str, Path]:
    engine: dict[str, Any] = {
        "type": "vllm_cuda_multi" if replica_devices else "vllm_cuda",
        "model_id": model_id,
        "gpu_image": DEFAULT_GPU_IMAGE,
        "max_model_len": engine_fields.pop("max_model_len", 16384),
        "tensor_parallel_size": engine_fields.pop("tensor_parallel_size", 1),
        "gpu_memory_utilization": engine_fields.pop("gpu_memory_utilization", 0.90),
        "port": 9100,
        "host": "127.0.0.1",
        "startup_timeout_s": 1800,
    }
    engine.update(engine_fields)          # e.g. quantization_kind
    if replica_devices:
        engine["replica_devices"] = [list(g) for g in replica_devices]
    elif gpu_device_ids:
        engine["gpu_device_ids"] = gpu_device_ids
    if extra_flags:
        engine["vllm_extra_flags"] = [str(f) for f in extra_flags]
    # No docker_volumes on purpose: the vllm_cuda launcher mounts the
    # RESOLVED hf cache (UI storage choice) when a profile doesn't pin one.
    doc = {
        "engine": engine,
        "telemetry": {
            "enable_pmu": True,
            "enable_memory_bandwidth": True,
            "enable_power": True,
            "enable_engine_metrics": True,
            "enable_gpu": True,
        },
        "output": {"db_directory": "runs"},
    }
    profile_name = f"optimized-{_slug(name_hint)}"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{profile_name}.yaml"
    header = [
        f"# {profile_name} — GENERATED by the optimizer's",
        "# \"use for benchmark\" promote. Re-promoting overwrites this file;",
        "# copy it under a new name before hand-editing.",
        "#",
        *[f"# {line}" for line in provenance],
    ]
    if warnings:
        header += ["#", *[f"# WARNING: {w}" for w in warnings]]
    path.write_text(
        "\n".join(header) + "\n\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)
    )
    return profile_name, path


def promote_search_winner(
    search_doc: dict, out_dir: Path = PROFILES_DIR,
) -> dict:
    """Profile from a guided-search result JSON (search.json)."""
    from .search import candidate_summary, load_space

    best = (search_doc.get("summary") or {}).get("best")
    if not best:
        raise PromoteError(
            "the search has no successful candidate yet — nothing to promote"
        )
    space_file = search_doc.get("space_file")
    if not space_file or not Path(space_file).exists():
        raise PromoteError(f"search space file not found: {space_file}")
    space = load_space(space_file)
    if search_doc.get("space_hash") != space.space_hash():
        raise PromoteError(
            "the search space changed since this result was produced — "
            "re-run the search before promoting"
        )
    summary = candidate_summary(best["params"], space)
    fields, leftover = parse_engine_args(list(summary["engine_args"]))
    fields.setdefault("tensor_parallel_size", summary["tp"])

    replicas = summary["replica_devices"]
    warnings = []
    multi = len(replicas) > 1
    if multi:
        warnings.append(
            f"dp={len(replicas)} winner — promoted as vllm_cuda_multi: "
            f"the benchmark drives ALL {len(replicas)} replicas with "
            f"sticky per-user routing (whole-box capacity, measured)."
        )
    score = best.get("score")
    result = _write_profile(
        name_hint=search_doc.get("space", "search"),
        model_id=str(summary["model"]),
        engine_fields=fields,
        extra_flags=leftover,
        gpu_device_ids=None if multi else replicas[0],
        replica_devices=replicas if multi else None,
        provenance=[
            f"source: guided search '{search_doc.get('space')}' "
            f"({search_doc.get('generated_at', '')[:19]})",
            f"winner: {best.get('key', '')}",
            f"score: {score:.1f}" if score is not None else "score: —",
        ],
        warnings=warnings,
        out_dir=out_dir,
    )
    return {"profile": result[0], "path": str(result[1]),
            "warnings": warnings, "winner": best.get("key", "")}


def promote_registry_winner(
    catalog: dict, results_doc: dict, config_name: str,
    out_dir: Path = PROFILES_DIR,
) -> dict:
    """Profile from a registry-sweep result (run.json) + the script's
    --list-json catalog (which carries each config's launch shape)."""
    reg_profile = results_doc.get("profile", "")
    result_entry = next(
        (c for c in results_doc.get("configs", [])
         if c.get("name") == config_name), None,
    )
    if result_entry is None:
        raise PromoteError(f"'{config_name}' is not in the sweep results")
    if result_entry.get("status") != "ok":
        raise PromoteError(
            f"'{config_name}' did not complete "
            f"({result_entry.get('status')}) — promote a config that ran"
        )
    cat_entry = next(
        (c for c in (catalog.get("profiles", {}).get(reg_profile) or [])
         if c.get("name") == config_name), None,
    )
    if cat_entry is None or "replica_args" not in cat_entry:
        raise PromoteError(
            f"the optimizer catalog has no launch shape for "
            f"'{config_name}' — update scripts/engine_optimizer.py "
            f"(old --list-json format?)"
        )
    fields, leftover = parse_engine_args(list(cat_entry["replica_args"]))
    replica_gpus = [g for g in (cat_entry.get("replica_gpus") or [])]
    multi_devices = None
    warnings = []
    if len(replica_gpus) > 1:
        parsed = [_parse_gpus(g) for g in replica_gpus]
        if all(parsed):
            multi_devices = parsed
            warnings.append(
                f"'{config_name}' runs {len(replica_gpus)} replicas — "
                f"promoted as vllm_cuda_multi (whole-box, sticky-routed)."
            )
        else:
            warnings.append(
                f"'{config_name}' runs {len(replica_gpus)} replicas with "
                f"unparseable GPU pins — promoted pinned to replica 0."
            )
    model = results_doc.get("model") or (
        catalog.get("profile_defaults", {}).get(reg_profile, {}).get("model")
    )
    if not model:
        raise PromoteError("results carry no model id — re-run the sweep")
    result = _write_profile(
        name_hint=f"{reg_profile}-{config_name}",
        model_id=str(model),
        engine_fields=fields,
        extra_flags=leftover,
        gpu_device_ids=(None if multi_devices
                        else _parse_gpus(replica_gpus[0]) if replica_gpus
                        else None),
        replica_devices=multi_devices,
        provenance=[
            f"source: registry sweep '{reg_profile}' "
            f"({results_doc.get('generated_at', '')[:19]})",
            f"winner: {config_name} — {cat_entry.get('description', '')}",
        ],
        warnings=warnings,
        out_dir=out_dir,
    )
    return {"profile": result[0], "path": str(result[1]),
            "warnings": warnings, "winner": config_name}


def space_overview(space) -> dict:
    """Compact space description for the UI's picker: what would this
    search actually cover?"""
    n_valid_dims = {d: len(v) for d, v in space.dimensions.items()}
    return {
        "name": space.name,
        "engine": space.engine,
        "models": {v: str(spec.get("model", ""))
                   for v, spec in space.model_variants.items()},
        "dimensions": n_valid_dims,
        "devices": space.total_devices,
        "device_groups": space.device_groups,
        "objective": space.objective.kind,
        "budget": space.search.budget,
        "initial_samples": space.search.initial_samples,
    }
