#!/usr/bin/env python3
"""Forklift the still-valid pieces of a finished ``run_NN/`` into a
fresh ``run_NN+1/`` so a normal ``make run-sweep`` resumes against a
clean baseline.

Use case: persona renames + cohort-mix changes have invalidated some
of an older run's cohort_runs, but the per-persona measurements are
still valid (same workload, just relabelled). This script copies
those over — DB rows AND associated ``perf_m<id>_*.csv`` files — into
a new run dir, leaving the source untouched. The resume logic in
``runner.run_sweep`` then sees the carried-over personas as already
``final_status='ok'`` and only runs what's missing (renamed personas
that didn't exist before, plus all five cohorts under their new
mixes).

What's carried over:
  * ``cohort_run`` rows whose ``cohort_id`` is a current persona
    (after the ``drafter → writer`` rename).
  * Their ``cohort_measurements``, ``turn_events``,
    ``measurement_telemetry``, ``simulation_snapshots``,
    ``virtual_users`` rows. Primary keys (``measurement_id``,
    ``event_id`` …) are preserved so the perf CSV filenames keep
    matching.
  * ``final_status='ok'`` only — partial / failed runs are dropped
    rather than re-imported.
  * Any ``perf_m<measurement_id>_*.csv`` files whose id is in the
    copied set.

What's NOT carried over:
  * Cohort runs (mixes changed — needs fresh measurement).
  * Personas that no longer exist (``ai_engineering``, the old
    ``engineering_heavy`` persona).
  * Engine / sweep logs (run-level, regenerated by the next run).

Usage:
    python scripts/forklift_run.py --source runs/run_03
        # auto-creates runs/run_04 and forklifts into it
    python scripts/forklift_run.py --source runs/run_03 --dest runs/run_99
        # explicit destination dir (created if missing)
    python scripts/forklift_run.py --source runs/run_03 --dry-run
        # report what would happen, write nothing
"""

from __future__ import annotations

import argparse
import shutil
import sqlite3
import sys
from pathlib import Path

# Make ``simulator.*`` importable when run from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from simulator.database import Database  # noqa: E402
from simulator.runs import next_run_dir   # noqa: E402


# Personas that exist in the current personas.py. cohort_run rows
# whose cohort_id is in this set are preserved (ephemeral
# one-persona cohorts). Anything else — cohort runs, removed
# personas — is dropped.
CURRENT_PERSONAS = {
    "quick_lookup",
    "conversational",
    "writer",
    "document_qa",
    "code_assist",
    "summarizer",
}

# Renames applied during forklift. Keys are old persona ids, values
# are the new ones. Any cohort_run / virtual_users / turn_events row
# referencing an old id is rewritten to the new one before insert.
PERSONA_RENAMES = {
    "drafter": "writer",
}


def _resolve_source_db(run_dir: Path) -> Path:
    """Locate the single ``run.db`` in a run directory."""
    candidates = list(run_dir.glob("run.db"))
    if candidates:
        return candidates[0]
    # Older layouts: per-cohort DB files. Refuse — those predate the
    # single-DB consolidation and aren't worth supporting.
    legacy = list(run_dir.glob("*.db"))
    if legacy:
        sys.exit(
            f"Source layout looks pre-consolidation ({len(legacy)} *.db files). "
            f"Forklift only supports single-run.db layouts."
        )
    sys.exit(f"No run.db in {run_dir}")


def _table_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    return [r[1] for r in conn.execute(f"PRAGMA table_info({table})")]


def _intersect_columns(
    src: sqlite3.Connection, dst: sqlite3.Connection, table: str,
) -> list[str]:
    """Return columns present in BOTH source and destination — defensive
    against schema drift between runs (older DBs missing newer cols).
    """
    src_cols = set(_table_columns(src, table))
    dst_cols = set(_table_columns(dst, table))
    common = src_cols & dst_cols
    # Preserve destination column order for readability of generated SQL.
    return [c for c in _table_columns(dst, table) if c in common]


def _row_to_dict(row: sqlite3.Row, columns: list[str]) -> dict[str, object]:
    return {c: row[c] for c in columns}


def _apply_persona_renames(value: object) -> object:
    """Map a persona_id-shaped string through ``PERSONA_RENAMES``."""
    if isinstance(value, str) and value in PERSONA_RENAMES:
        return PERSONA_RENAMES[value]
    return value


def _rewrite_cohort_definition_json(text: str) -> str:
    """In-place replace old persona ids in the JSON blob.

    For a one-persona ephemeral cohort, the JSON contains the persona
    id as a string — straight token replacement is good enough since
    persona ids don't collide with JSON syntax.
    """
    if not text:
        return text
    out = text
    for old, new in PERSONA_RENAMES.items():
        out = out.replace(f'"{old}"', f'"{new}"')
    return out


def forklift(source_dir: Path, dest_dir: Path, *, dry_run: bool) -> None:
    src_db_path = _resolve_source_db(source_dir)
    dst_db_path = dest_dir / "run.db"

    print(f"Source : {src_db_path}")
    print(f"Dest   : {dst_db_path}{' (dry-run)' if dry_run else ''}")

    src = sqlite3.connect(src_db_path)
    src.row_factory = sqlite3.Row

    # Build the dest DB with the current schema (including all
    # idempotent migrations). Even in --dry-run we open it, but
    # against an in-memory DB so we get the schema for column
    # diffing without touching disk.
    if dry_run:
        # Use an in-memory DB initialised with the same schema, so
        # _intersect_columns sees what a fresh DB would have.
        tmp = Database(":memory:")
        dst = tmp._conn  # noqa: SLF001 — same module's wrapper
    else:
        dest_dir.mkdir(parents=True, exist_ok=True)
        if dst_db_path.exists():
            sys.exit(f"Refusing to overwrite existing {dst_db_path}")
        Database(str(dst_db_path)).close()
        dst = sqlite3.connect(dst_db_path)
        dst.row_factory = sqlite3.Row
        dst.execute("PRAGMA foreign_keys=OFF")

    # ── 1. Pick keepable cohort_run rows ────────────────────────────
    keep_rows: list[sqlite3.Row] = []
    cr_columns = _intersect_columns(src, dst, "cohort_run")
    rows = src.execute(
        f"SELECT {', '.join(cr_columns)} FROM cohort_run"
    ).fetchall()
    skipped_status: list[str] = []
    skipped_ident: list[str] = []
    for r in rows:
        cohort_id = r["cohort_id"]
        renamed = PERSONA_RENAMES.get(cohort_id, cohort_id)
        if renamed not in CURRENT_PERSONAS:
            skipped_ident.append(cohort_id)
            continue
        if r["final_status"] != "ok":
            skipped_status.append(f"{cohort_id} ({r['final_status']!r})")
            continue
        keep_rows.append(r)

    print(f"\ncohort_run: keeping {len(keep_rows)}, "
          f"skipping {len(skipped_ident)} non-current + "
          f"{len(skipped_status)} not-ok")
    for s in skipped_ident:
        print(f"  drop (not current persona): {s}")
    for s in skipped_status:
        print(f"  drop (status):              {s}")
    for r in keep_rows:
        old = r["cohort_id"]
        new = PERSONA_RENAMES.get(old, old)
        tag = f" → {new}" if new != old else ""
        print(f"  keep: {old}{tag}  ({r['cohort_run_id']})")

    if not keep_rows:
        print("\nNothing to forklift.")
        if not dry_run:
            dst.close()
        return

    keep_run_ids = [r["cohort_run_id"] for r in keep_rows]

    # ── 2. Insert cohort_run rows (with renames applied) ────────────
    if not dry_run:
        for r in keep_rows:
            d = _row_to_dict(r, cr_columns)
            d["cohort_id"] = PERSONA_RENAMES.get(d["cohort_id"], d["cohort_id"])
            if "cohort_definition_json" in d and isinstance(
                d["cohort_definition_json"], str
            ):
                d["cohort_definition_json"] = _rewrite_cohort_definition_json(
                    d["cohort_definition_json"]
                )
            placeholders = ", ".join(["?"] * len(cr_columns))
            dst.execute(
                f"INSERT INTO cohort_run ({', '.join(cr_columns)}) "
                f"VALUES ({placeholders})",
                [d[c] for c in cr_columns],
            )

    # ── 3. Copy child rows (cohort_measurements + descendants) ──────
    placeholders_in = ", ".join(["?"] * len(keep_run_ids))

    # cohort_measurements (parent of turn_events, measurement_telemetry).
    cm_columns = _intersect_columns(src, dst, "cohort_measurements")
    cm_rows = src.execute(
        f"SELECT {', '.join(cm_columns)} FROM cohort_measurements "
        f"WHERE cohort_run_id IN ({placeholders_in})",
        keep_run_ids,
    ).fetchall()
    keep_measurement_ids = [r["measurement_id"] for r in cm_rows]
    print(f"cohort_measurements: {len(cm_rows)} rows")

    if not dry_run and cm_rows:
        placeholders = ", ".join(["?"] * len(cm_columns))
        dst.executemany(
            f"INSERT INTO cohort_measurements ({', '.join(cm_columns)}) "
            f"VALUES ({placeholders})",
            [[r[c] for c in cm_columns] for r in cm_rows],
        )

    # turn_events — apply persona_id rename.
    te_columns = _intersect_columns(src, dst, "turn_events")
    te_rows = []
    if keep_measurement_ids:
        te_placeholders_in = ", ".join(["?"] * len(keep_measurement_ids))
        te_rows = src.execute(
            f"SELECT {', '.join(te_columns)} FROM turn_events "
            f"WHERE measurement_id IN ({te_placeholders_in})",
            keep_measurement_ids,
        ).fetchall()
    print(f"turn_events:         {len(te_rows)} rows")
    if not dry_run and te_rows:
        placeholders = ", ".join(["?"] * len(te_columns))
        batch = []
        for r in te_rows:
            d = _row_to_dict(r, te_columns)
            if "persona_id" in d:
                d["persona_id"] = _apply_persona_renames(d["persona_id"])
            batch.append([d[c] for c in te_columns])
        dst.executemany(
            f"INSERT INTO turn_events ({', '.join(te_columns)}) "
            f"VALUES ({placeholders})",
            batch,
        )

    # measurement_telemetry — no persona_id, simple copy.
    mt_columns = _intersect_columns(src, dst, "measurement_telemetry")
    mt_rows = []
    if keep_measurement_ids:
        mt_placeholders_in = ", ".join(["?"] * len(keep_measurement_ids))
        mt_rows = src.execute(
            f"SELECT {', '.join(mt_columns)} FROM measurement_telemetry "
            f"WHERE measurement_id IN ({mt_placeholders_in})",
            keep_measurement_ids,
        ).fetchall()
    print(f"measurement_telemetry: {len(mt_rows)} rows")
    if not dry_run and mt_rows:
        placeholders = ", ".join(["?"] * len(mt_columns))
        dst.executemany(
            f"INSERT INTO measurement_telemetry ({', '.join(mt_columns)}) "
            f"VALUES ({placeholders})",
            [[r[c] for c in mt_columns] for r in mt_rows],
        )

    # simulation_snapshots — keyed on cohort_run_id, simple copy.
    ss_columns = _intersect_columns(src, dst, "simulation_snapshots")
    ss_rows = src.execute(
        f"SELECT {', '.join(ss_columns)} FROM simulation_snapshots "
        f"WHERE cohort_run_id IN ({placeholders_in})",
        keep_run_ids,
    ).fetchall()
    print(f"simulation_snapshots:  {len(ss_rows)} rows")
    if not dry_run and ss_rows:
        placeholders = ", ".join(["?"] * len(ss_columns))
        dst.executemany(
            f"INSERT INTO simulation_snapshots ({', '.join(ss_columns)}) "
            f"VALUES ({placeholders})",
            [[r[c] for c in ss_columns] for r in ss_rows],
        )

    # virtual_users — apply persona_id rename.
    vu_columns = _intersect_columns(src, dst, "virtual_users")
    vu_rows = src.execute(
        f"SELECT {', '.join(vu_columns)} FROM virtual_users "
        f"WHERE cohort_run_id IN ({placeholders_in})",
        keep_run_ids,
    ).fetchall()
    print(f"virtual_users:         {len(vu_rows)} rows")
    if not dry_run and vu_rows:
        placeholders = ", ".join(["?"] * len(vu_columns))
        batch = []
        for r in vu_rows:
            d = _row_to_dict(r, vu_columns)
            if "persona_id" in d:
                d["persona_id"] = _apply_persona_renames(d["persona_id"])
            batch.append([d[c] for c in vu_columns])
        dst.executemany(
            f"INSERT INTO virtual_users ({', '.join(vu_columns)}) "
            f"VALUES ({placeholders})",
            batch,
        )

    # ── 4. Copy perf_m<id>_*.csv files matching kept measurement_ids ─
    keep_id_set = set(keep_measurement_ids)
    csvs = list(source_dir.glob("perf_m*_*.csv"))
    copied_csvs = 0
    for csv in csvs:
        # filename pattern: perf_m<measurement_id>_<pool>.csv
        name = csv.name
        try:
            mid_str = name.removeprefix("perf_m").split("_", 1)[0]
            mid = int(mid_str)
        except (ValueError, IndexError):
            continue
        if mid not in keep_id_set:
            continue
        if not dry_run:
            shutil.copy2(csv, dest_dir / csv.name)
        copied_csvs += 1
    print(f"perf csv files: copying {copied_csvs} of {len(csvs)}")

    if not dry_run:
        dst.commit()
        dst.close()
    print(f"\nDone. Resume with: make run-sweep ARGS='...' "
          f"(reads from {dest_dir})")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", required=True, type=Path,
                   help="Source run dir (e.g. runs/run_03)")
    p.add_argument("--dest", type=Path, default=None,
                   help="Destination run dir. Default: next run_NN under "
                        "the source's parent.")
    p.add_argument("--dry-run", action="store_true",
                   help="Report what would be copied; write nothing.")
    args = p.parse_args()

    if not args.source.exists():
        sys.exit(f"Source dir not found: {args.source}")

    if args.dest is None:
        dest = next_run_dir(args.source.parent) if not args.dry_run \
            else args.source.parent / "run_NN+1 (auto)"
    else:
        dest = args.dest

    forklift(args.source, dest, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
